### ISSUE TITLE
img2pdf python 3 issue

### ISSUE THREAD

**Issue by GhostofGoes** [yodiaditya/slideshare-downloader#2]
The current version of img2pdf only works for python 3.
Requirements.txt needed to be amended to "img2pdf==0.1.3"

**Comment by yodiaditya** [comment]
Bug fixed and upgraded with latest version work with Slideshare 2024 layout. Thank you @GhostofGoes !

**Comment by GhostofGoes** [comment]
Man, I opened this issue nearly 8 years ago back when I still used this tool and Python 2 for things. That being said, THANK YOU for taking the time to go back and address issues, not all heroes wear capes 😺

**Comment by yodiaditya** [comment]
Hey @GhostofGoes, your kind words made my day!
