### ISSUE TITLE
Use /tmp for storing images

### ISSUE THREAD

**Issue by kanihal** [yodiaditya/slideshare-downloader#5]
store images in subdirectory in `/tmp`  so that they get flushed on restart.

And also, `slideshare2pdf.py` would be a better name than `convert.py`

**Comment by mrlexley** [comment]
And use 
        r = requests.get(image_url)
        if not os.path.exists(title):
            os.makedirs(title)
        with open(title+"/"+filename, 'wb') as f:  
           f.write(r.content)
instead of wget command, this is more os generic.

**Comment by yodiaditya** [comment]
Bug fixed and upgraded with latest version work with Slideshare 2024 layout. Thank you @kanihal  @mrlexley  !
